---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Content
- type: document
  path: content/home.md
  label: Home
- type: directory
  path: content/pages
  label: Pages
  create: all
  match: "**/*"
  templates:
  - page
- type: directory
  path: content/jobs
  label: Jobs
  create: all
  match: "**/*"
  templates:
  - job-post
- type: directory
  path: content/events
  label: Events
  create: all
  match: "**/*"
  templates:
  - event
upload_dir: public/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".next"
  install_dependencies_command: npm ci
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
